In [1]:
import pandas as pd

In [2]:
df_price = pd.read_csv("price_paid_records.csv")
df_price

,Transaction unique identifier,Price,Date of Transfer,Property Type,Old/New,Duration,Town/City,District,County,PPDCategory Type,Record Status - monthly file only
0,{81B82214-7FBC-4129-9F6B-4956B4A663AD},25000,1995-08-18 00:00,T,N,F,OLDHAM,OLDHAM,GREATER MANCHESTER,A,A
1,{8046EC72-1466-42D6-A753-4956BF7CD8A2},42500,1995-08-09 00:00,S,N,F,GRAYS,THURROCK,THURROCK,A,A
2,{278D581A-5BF3-4FCE-AF62-4956D87691E6},45000,1995-06-30 00:00,T,N,F,HIGHBRIDGE,SEDGEMOOR,SOMERSET,A,A
3,{1D861C06-A416-4865-973C-4956DB12CD12},43150,1995-11-24 00:00,T,N,F,BEDFORD,NORTH BEDFORDSHIRE,BEDFORDSHIRE,A,A
4,{DD8645FD-A815-43A6-A7BA-4956E58F1874},18899,1995-06-23 00:00,S,N,F,WAKEFIELD,LEEDS,WEST YORKSHIRE,A,A
...,...,...,...,...,...,...,...,...,...,...,...
22489343,{4C4EE000-291A-1854-E050-A8C063054F34},175000,2017-02-20 00:00,S,N,F,LEEDS,LEEDS,WEST YORKSHIRE,A,A
22489344,{4C4EE000-291B-1854-E050-A8C063054F34},586945,2017-02-15 00:00,D,N,F,WETHERBY,LEEDS,WEST YORKSHIRE,A,A
22489345,{4C4EE000-291C-1854-E050-A8C063054F34},274000,2017-02-24 00:00,D,N,L,HUDDERSFIELD,KIRKLEES,WEST YORKSHIRE,A,A
22489346,{4C4EE000-291D-1854-E050-A8C063054F34},36000,2017-02-22 00:00,T,N,F,HALIFAX,CALDERDALE,WEST YORKSHIRE,A,A
22489347,{4C4EE000-291E-1854-E050-A8C063054F34},145000,2017-03-03 00:00,T,N,F,LEEDS,LEEDS,WEST YORKSHIRE,A,A

In [11]:
#mapper 1
sr_date =  df_price['Date of Transfer']
lst_year = []
for date in sr_date:
    year = date.split('-')
    lst_year.append((year[0],1))
lst_year

[('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ('1995', 1),
 ...]

In [12]:
#ordenar
lst_year.sort()

In [15]:
#reducer
srs_years = pd.Series(lst_year)
srs_years.value_counts()

(2002, 1)    1351256
(2006, 1)    1326161
(2007, 1)    1272921
(2004, 1)    1270409
(2003, 1)    1257140
(2001, 1)    1245112
(1999, 1)    1194064
(2000, 1)    1128742
(1997, 1)    1093669
(2005, 1)    1061686
(1998, 1)    1049739
(2016, 1)    1032558
(2015, 1)    1007421
(2014, 1)     982943
(1996, 1)     964695
(2013, 1)     810111
(1995, 1)     796777
(2012, 1)     668295
(2010, 1)     663342
(2011, 1)     661055
(2008, 1)     650492
(2009, 1)     625662
(2017, 1)     375098
dtype: int64

In [28]:
#Town/City
#price
df_prom = pd.DataFrame(df_price['Town/City'])
df_prom['Price'] = df_price['Price']
df_prom

             Town/City   Price
0               OLDHAM   25000
1                GRAYS   42500
2           HIGHBRIDGE   45000
3              BEDFORD   43150
4            WAKEFIELD   18899
...                ...     ...
22489343         LEEDS  175000
22489344      WETHERBY  586945
22489345  HUDDERSFIELD  274000
22489346       HALIFAX   36000
22489347         LEEDS  145000

[22489348 rows x 2 columns]

In [32]:
lst_prom = []
for fill,row in df_prom.iterrows():
    lst_prom.append((row['Town/City'],row['Price']))
lst_prom

 67000),
 ('BEVERLEY', 27000),
 ('LEAMINGTON SPA', 100700),
 ('NEWTON-LE-WILLOWS', 41000),
 ('LONDON', 180000),
 ('NORTHAMPTON', 63500),
 ('WARRINGTON', 116750),
 ('BURGESS HILL', 62800),
 ('ALTON', 59500),
 ('TELFORD', 69950),
 ('BALDOCK', 35200),
 ('DUNSTABLE', 31000),
 ('NEWBURY', 142000),
 ('CHARD', 26500),
 ('WILMSLOW', 61500),
 ('DIDCOT', 59999),
 ('SOUTHAMPTON', 69950),
 ('GRANTHAM', 23950),
 ('NEWMARKET', 48500),
 ('NORTHAMPTON', 43500),
 ('MIDHURST', 48000),
 ('BRIERLEY HILL', 64950),
 ('UXBRIDGE', 124500),
 ('BIRMINGHAM', 48950),
 ('DOVER', 147000),
 ('YEOVIL', 64000),
 ('BURGESS HILL', 59000),
 ('LEICESTER', 57000),
 ('SHEFFIELD', 26500),
 ('OXTED', 136000),
 ('OXFORD', 62000),
 ('PORTHCAWL', 52000),
 ('HEREFORD', 77000),
 ('SEVENOAKS', 88000),
 ('CHELMSFORD', 58000),
 ('COLCHESTER', 46000),
 ('LONDON', 90000),
 ('COLCHESTER', 30000),
 ('WALLASEY', 81000),
 ('BRISTOL', 46500),
 ('MANCHESTER', 51500),
 ('BUCKINGHAM', 54000),
 ('FARNBOROUGH', 60000),
 ('FELIXSTOWE', 69500),
 ('LONDON', 145000),
 ('LIVERPOOL', 35000),
 ('BRENTWOOD', 75000),
 ('COLWYN BAY', 27000),
 ('NEWPORT', 46500),
 ('LINCOLN', 34500),
 ('HEREFORD', 49000),
 ('LONDON', 143000),
 ('BOREHAMWOOD', 47000),
 ('SUTTON COLDFIELD', 59950),
 ('ADDLESTONE', 40000),
 ('NEWCASTLE UPON TYNE', 37100),
 ('NUNEATON', 59000),
 ('LOUGHBOROUGH', 137500),
 ('CARSHALTON', 60000),
 ('LONDON', 65000),
 ('LONDON', 87500),
 ('BRACKLEY', 55500),
 ('MANCHESTER', 22500),
 ('ALTRINCHAM', 86750),
 ('HUNTINGDON', 63200),
 ('SHEFFIELD', 68000),
 ('MANCHESTER', 35500),
 ('BRADFORD', 20500),
 ('LEICESTER', 51000),
 ('GLOSSOP', 25000),
 ('LONDON', 81000),
 ('SUDBURY', 44000),
 ('SOUTH CROYDON', 88500),
 ('BENFLEET', 52995),
 ('LEIGH-ON-SEA', 23500),
 ('HUDDERSFIELD', 40500),
 ('READING', 127500),
 ('ROMSEY', 56000),
 ('OLDHAM', 30350),
 ('HEMEL HEMPSTEAD', 45500),
 ('WIGAN', 37000),
 ('COLWYN BAY', 37500),
 ('LONDON', 235000),
 ('LIVERPOOL', 10000),
 ('MANCHESTER', 52000),
 ('WALTON ON THE NAZE', 15000),
 ('EBBW VALE', 18000),
 ('SOUTHSEA', 49000),
 ('MORECAMBE', 33500),
 ('HORNCHURCH', 73000),
 ('CHESTERFIELD', 6950),
 ('AYLESFORD', 48000),
 ('HEREFORD', 85000),
 ('KEIGHLEY', 46500),
 ('GRIMSBY', 56950),
 ('MAIDSTONE', 72500),
 ('HALIFAX', 49950),
 ('BILLINGHAM', 53750),
 ('BARRY', 44500),
 ('LEICESTER', 46950),
 ('CAMBRIDGE', 79000),
 ('BRIDGEND', 46500),
 ('GRAYS', 54995),
 ('BARNSLEY', 40500),
 ('HOVE', 23000),
 ('CAERPHILLY', 36000),
 ('BARKING', 55500),
 ('BOGNOR REGIS', 122000),
 ('MAIDSTONE', 110000),
 ('MAIDSTONE', 87500),
 ('LITTLEHAMPTON', 85000),
 ('IPSWICH', 41000),
 ('AYLESBURY', 172000),
 ('TORQUAY', 59000),
 ('BOGNOR REGIS', 14000),
 ('DUNSTABLE', 312000),
 ('CAMBERLEY', 59950),
 ('LONDON', 70000),
 ('LOWESTOFT', 36000),
 ('WIGAN', 59750),
 ('READING', 145000),
 ('CHORLEY', 59000),
 ('HOLMFIRTH', 45000),
 ('TELFORD', 63000),
 ('MALDON', 140995),
 ('SOUTHAMPTON', 48000),
 ('HAYLE', 39000),
 ('LUTTERWORTH', 150000),
 ('STOCKPORT', 55000),
 ('NEWBURY', 49250),
 ('HALESOWEN', 44000),
 ('WELWYN GARDEN CITY', 135500),
 ('MANCHESTER', 15000),
 ('WEYBRIDGE', 275000),
 ('LIVERPOOL', 44475),
 ('WASHINGTON', 29950),
 ('BLYTH', 18000),
 ('MITCHAM', 55950),
 ('MANSFIELD', 15000),
 ('LONDON', 206950),
 ('HINCKLEY', 25500),
 ('BLACKBURN', 33000),
 ('LLANDUDNO JUNCTION', 35000),
 ('WORCESTER PARK', 86850),
 ('GUILDFORD', 59850),
 ('NOTTINGHAM', 30000),
 ('STOCKPORT', 153000),
 ('SIDCUP', 85000),
 ('OAKHAM', 65500),
 ('BIRMINGHAM', 28500),
 ('HITCHIN', 95000),
 ('CHESTER', 52000),
 ('ALDERSHOT', 83000),
 ('CARTERTON', 70000),
 ('ALTRINCHAM', 57500),
 ('SHREWSBURY', 38500),
 ('DERBY', 29995),
 ('SWANSEA', 21500),
 ('CALDICOT', 78500),
 ('HOLMROOK', 65000),
 ('MIDDLESBROUGH', 30000),
 ('DARLINGTON', 70000),
 ('HARWICH', 52000),
 ('LIVERPOOL', 24000),
 ('LEICESTER', 51000),
 ('SUTTON COLDFIELD', 79000),
 ('LEYLAND', 28000),
 ('LONDON', 156000),
 ('BASINGSTOKE', 60000),
 ('LEICESTER', 53500),
 ('OLDHAM', 34000),
 ('SOUTH OCKENDON', 55000),
 ('HIGHBRIDGE', 20000),
 ('SWANLEY', 57995),
 ('BOLTON', 29000),
 ('LONDON', 75500),
 ('OXFORD', 137000),
 ('SOWERBY BRIDGE', 34000),
 ('ST. IVES', 57000),
 ('BARNET', 80000),
 ('PEACEHAVEN', 48000),
 ('WETHERBY', 67500),
 ('NORTH WALSHAM', 48950),
 ('SWINDON', 39000),
 ('BIRMINGHAM', 70000),
 ('MARCH', 59000),
 ('BIRMINGHAM', 64000),
 ('TEDDINGTON', 169250),
 ('DURHAM', 41000),
 ('NORMANTON', 70000),
 ('LONDON', 52000),
 ('LETCHWORTH GARDEN CITY', 140000),
 ('MANCHESTER', 27000),
 ('BRADFORD', 35000),
 ('RICHMOND', 258500),
 ('HAVERFORDWEST', 35000),
 ('LYME REGIS', 41500),
 ('LOOE', 75000),
 ('WIMBORNE', 52000),
 ('POTTERS BAR', 84000),
 ('FARNBOROUGH', 69950),
 ('LEICESTER', 75000),
 ('LONDON', 67000),
 ('HENFIELD', 92000),
 ('PENZANCE', 41000),
 ('TWICKENHAM', 64950),
 ('GUILDFORD', 68000),
 ('PONTYPRIDD', 42500),
 ('CRAWLEY', 56000),
 ('TIVERTON', 60000),
 ('SMETHWICK', 18750),
 ('HARPENDEN', 62000),
 ('ARUNDEL', 216000),
 ('CHELTENHAM', 86500),
 ('CAMBRIDGE', 275000),
 ('OLDBURY', 37000),
 ('WEYMOUTH', 93750),
 ('BRIGHTON', 35050),
 ('LONDON', 82500),
 ('STOCKTON-ON-TEES', 65000),
 ('BURY ST. EDMUNDS', 69995),
 ('LEICESTER', 64000),
 ('POOLE', 75500),
 ('NORTH SHIELDS', 37500),
 ('SUNDERLAND', 64450),
 ('NARBERTH', 55000),
 ('NORTHAMPTON', 87000),
 ('BRIDLINGTON', 35000),
 ('FELIXSTOWE', 86500),
 ('BILSTON', 37000),
 ('SUTTON', 60000),
 ('TUNBRIDGE WELLS', 160000),
 ('WHITSTABLE', 47000),
 ('HUNTINGDON', 20625),
 ('READING', 58500),
 ('BROMLEY', 132000),
 ('BEDFORD', 98000),
 ('DURHAM', 60000),
 ('MORPETH', 19000),
 ('LONDON', 134000),
 ('LONDON', 52995),
 ('EDGWARE', 79950),
 ('NEWCASTLE UPON TYNE', 133000),
 ('SWANSEA', 32995),
 ('CONISTON', 151500),
 ('CANNOCK', 43000),
 ('LIVERPOOL', 39000),
 ('MORDEN', 69500),
 ('STRATFORD-UPON-AVON', 44000),
 ('LIVERPOOL', 32000),
 ('CHELMSFORD', 74775),
 ('BEDFORD', 79995),
 ('HARLOW', 59995),
 ('BIRKENHEAD', 75000),
 ('GLOUCESTER', 63250),
 ('LOWESTOFT', 70250),
 ('BEDWORTH', 23000),
 ('SALE', 38000),
 ('FALMOUTH', 38000),
 ('STOKE-ON-TRENT', 64000),
 ('STOKE-ON-TRENT', 35500),
 ('PETERBOROUGH', 88000),
 ('HENLEY-ON-THAMES', 229950),
 ('MANSFIELD', 20500),
 ('ASHFORD', 53500),
 ('WIMBORNE', 81500),
 ('BRIGHTON', 67500),
 ('LEIGHTON BUZZARD', 59950),
 ('WOLVERHAMPTON', 57250),
 ('BRISTOL', 39000),
 ('CHESTERFIELD', 16000),
 ('LOUGHTON', 99495),
 ('SUTTON COLDFIELD', 93000),
 ('ASHTON-UNDER-LYNE', 49500),
 ('LONDON', 69500),
 ('PLYMOUTH', 41950),
 ('SCARBOROUGH', 25000),
 ('PAIGNTON', 45000),
 ('HULL', 15000),
 ('DONCASTER', 47000),
 ('CHIPPING CAMPDEN', 160000),
 ('SHEFFIELD', 56000),
 ('KEIGHLEY', 49500),
 ('COLWYN BAY', 69000),
 ('BRISTOL', 59999),
 ('GUILDFORD', 79000),
 ('LONDON', 124000),
 ('LEICESTER', 26000),
 ('WINCHESTER', 149995),
 ('LICHFIELD', 60000),
 ('COLCHESTER', 100000),
 ('PONTYPRIDD', 38500),
 ('KENILWORTH', 83000),
 ('CHORLEY', 56000),
 ('MANCHESTER', 20060),
 ('HOLYWELL', 97000),
 ('NEWCASTLE', 33000),
 ('ASHFORD', 40500),
 ('TAMWORTH', 48750),
 ('LOWESTOFT', 40000),
 ('WARRINGTON', 90000),
 ('SWINDON', 32500),
 ('LONDON', 64995),
 ('LONDON', 84500),
 ('MORECAMBE', 39000),
 ('BASILDON', 55995),
 ('DONCASTER', 40000),
 ('CHIPPING CAMPDEN', 130000),
 ('MANNINGTREE', 64000),
 ('WEST MOLESEY', 87000),
 ('STOKE-ON-TRENT', 23000),
 ('DONCASTER', 43500),
 ('HEREFORD', 52000),
 ('LONDON', 280000),
 ('CROYDON', 66000),
 ('BRIGHTON', 32500),
 ('ESHER', 85500),
 ('WEMBLEY', 78000),
 ('DARTFORD', 125000),
 ('IPSWICH', 38000),
 ('NOTTINGHAM', 33500),
 ('COLCHESTER', 40000),
 ('BOREHAMWOOD', 42000),
 ('PETERBOROUGH', 38000),
 ('GOOLE', 65000),
 ('MANSFIELD', 28000),
 ('PORTSMOUTH', 50000),
 ('LOOE', 39000),
 ('ROMNEY MARSH', 35000),
 ('WALTON ON THE NAZE', 61000),
 ('BASINGSTOKE', 65000),
 ('FAREHAM', 82000),
 ('BRADFORD', 20000),
 ('NEWCASTLE UPON TYNE', 46000),
 ('WALLSEND', 33000),
 ('WADHURST', 90000),
 ('NOTTINGHAM', 44750),
 ('LEIGH', 31000),
 ('GREAT YARMOUTH', 80000),
 ('MARKFIELD', 79950),
 ('CHESTERFIELD', 40000),
 ('Y FELINHELI', 35000),
 ('BEVERLEY', 48950),
 ('NEWCASTLE UPON TYNE', 22948),
 ('GREENFORD', 73000),
 ('COLCHESTER', 52450),
 ('BENFLEET', 68000),
 ('PONTYPOOL', 34000),
 ('SUTTON COLDFIELD', 25000),
 ('CLEVEDON', 46000),
 ('CHESTERFIELD', 35500),
 ('SMETHWICK', 40000),
 ('BURY', 80000),
 ('ANDOVER', 42000),
 ('HUDDERSFIELD', 37000),
 ('ST. HELENS', 55000),
 ('WETHERBY', 54250),
 ('NOTTINGHAM', 46000),
 ('LONDON', 60000),
 ('WOODBRIDGE', 36000),
 ('SOUTHAMPTON', 50000),
 ('LONDON', 66500),
 ('EASTBOURNE', 58250),
 ('CHESTER LE STREET', 50000),
 ('LETCHWORTH GARDEN CITY', 32000),
 ('FOLKESTONE', 45700),
 ('DONCASTER', 17000),
 ('CHESTER', 74000),
 ('SHEFFIELD', 39500),
 ('LONDON', 200500),
 ('CAMBRIDGE', 76500),
 ('SOUTHAMPTON', 38000),
 ('BURRY PORT', 49995),
 ('NOTTINGHAM', 225000),
 ('MAESTEG', 12000),
 ('TEDDINGTON', 110000),
 ('BRADFORD', 33500),
 ('WEDNESBURY', 28000),
 ('DARWEN', 32000),
 ('POOLE', 58000),
 ('TADLEY', 42500),
 ('HEYWOOD', 33250),
 ('WAKEFIELD', 43000),
 ('CAMBRIDGE', 103540),
 ('CRICKHOWELL', 116250),
 ('BRAINTREE', 94995),
 ('RIPON', 51000),
 ('BURNLEY', 14000),
 ('EDGWARE', 66500),
 ('LIVERPOOL', 10500),
 ('MOUNTAIN ASH', 57000),
 ('CRAWLEY', 83000),
 ('ALTON', 142500),
 ('NEWCASTLE', 58500),
 ('BOURNE', 71000),
 ('ST. IVES', 51000),
 ('KETTERING', 67000),
 ('NORWICH', 29950),
 ('ANDOVER', 56000),
 ('BRIDGEND', 55000),
 ('CLEETHORPES', 98000),
 ('BURTON-ON-TRENT', 20000),
 ('GOSPORT', 52000),
 ('DEWSBURY', 38500),
 ('MANCHESTER', 36950),
 ('WAKEFIELD', 66000),
 ('NORTHAMPTON', 32000),
 ('LONGFIELD', 111000),
 ('LONDON', 183000),
 ('RUSHDEN', 35000),
 ('DAVENTRY', 57500),
 ('NEWTON ABBOT', 29750),
 ('BIRMINGHAM', 25500),
 ('PENZANCE', 125000),
 ('LIVERPOOL', 47500),
 ('LEICESTER', 35000),
 ('RIPLEY', 26500),
 ('LONGFIELD', 59500),
 ('LONDON', 87950),
 ('ROSS-ON-WYE', 217500),
 ('WATFORD', 64000),
 ('BOREHAMWOOD', 43500),
 ('WADEBRIDGE', 29950),
 ('CHICHESTER', 115000),
 ('MANCHESTER', 37000),
 ('BICESTER', 56000),
 ('SOLIHULL', 66750),
 ('NORTHAMPTON', 34000),
 ('MELTON CONSTABLE', 81500),
 ('WITHAM', 51500),
 ('WITHAM', 64750),
 ('READING', 46000),
 ('KETTERING', 29000),
 ('ILKLEY', 90000),
 ('SANDBACH', 160000),
 ('NEWENT', 68000),
 ('BILLERICAY', 31000),
 ('HOUNSLOW', 69000),
 ('BEDFORD', 132651),
 ('NOTTINGHAM', 52000),
 ('BIRMINGHAM', 51500),
 ('ROCHESTER', 43500),
 ('CHICHESTER', 102500),
 ('NOTTINGHAM', 49000),
 ('NEWPORT', 36000),
 ('BIRMINGHAM', 38000),
 ('BIRMINGHAM', 102000),
 ('WORKSOP', 75000),
 ('OSSETT', 28500),
 ('LONDON', 270000),
 ('NEWCASTLE', 30000),
 ('NORWICH', 35000),
 ('WARRINGTON', 35000),
 ('SOUTHAMPTON', 54500),
 ('LONDON', 110000),
 ('DERBY', 66000),
 ('KETTERING', 40000),
 ('WARRINGTON', 83950),
 ('ST. IVES', 53000),
 ('WORCESTER', 54500),
 ('BURNLEY', 80500),
 ('CASTLEFORD', 36000),
 ('BROADSTAIRS', 55000),
 ('LIVERPOOL', 59500),
 ('SMETHWICK', 44000),
 ('YORK', 39000),
 ('CANNOCK', 47000),
 ('ROTHERHAM', 71500),
 ('BIRMINGHAM', 45000),
 ('HAVANT', 47000),
 ('SANDWICH', 49500),
 ('AYLESBURY', 53500),
 ('WIGAN', 32500),
 ('ADDLESTONE', 118000),
 ('WETHERBY', 134500),
 ('FOLKESTONE', 68000),
 ('BRISTOL', 47000),
 ('SOUTH CROYDON', 108000),
 ('NEW MALDEN', 143000),
 ('KETTERING', 82000),
 ('WEMBLEY', 60000),
 ('LANCING', 35000),
 ('WOKINGHAM', 73000),
 ('TROWBRIDGE', 48000),
 ('SOUTHEND-ON-SEA', 39950),
 ('SCUNTHORPE', 108000),
 ('DARTMOUTH', 180000),
 ('BORDON', 49000),
 ('STOCKPORT', 60000),
 ('WARE', 42000),
 ('SELBY', 86000),
 ('LONDON', 110000),
 ('SANDOWN', 92000),
 ('NEWPORT PAGNELL', 46000),
 ('HORSHAM', 84000),
 ('HULL', 35000),
 ('HALIFAX', 51500),
 ('FOLKESTONE', 8500),
 ('HOUNSLOW', 76000),
 ('NOTTINGHAM', 32500),
 ('BEXHILL-ON-SEA', 113000),
 ('OXFORD', 73500),
 ('TONYPANDY', 16150),
 ('CRAWLEY', 59950),
 ('LONDON', 60950),
 ('HAVERFORDWEST', 68000),
 ('COVENTRY', 15000),
 ('STRATFORD-UPON-AVON', 56500),
 ('LONDON', 62950),
 ("KING'S LYNN", 19500),
 ('DAVENTRY', 33250),
 ('GREAT YARMOUTH', 79950),
 ('ALDERSHOT', 68950),
 ('WATERLOOVILLE', 54000),
 ('LONDON', 115000),
 ('ACCRINGTON', 37500),
 ('MANSFIELD', 40000),
 ('MORDEN', 84000),
 ('BRIXHAM', 41500),
 ('MACCLESFIELD', 55000),
 ('LONDON', 87500),
 ('Y FELINHELI', 36000),
 ('SWINDON', 67000),
 ('STONEHOUSE', 50500),
 ('ATHERSTONE', 85000),
 ('BARNSTAPLE', 35000),
 ('CWMBRAN', 15500),
 ('BOOTLE', 32500),
 ('MIDDLESBROUGH', 81995),
 ('BENFLEET', 31250),
 ('READING', 23000),
 ('BUILTH WELLS', 115000),
 ('GREENFORD', 114500),
 ('BRIXHAM', 81500),
 ('SHEFFIELD', 57000),
 ('UTTOXETER', 40000),
 ('HERTFORD', 107500),
 ('WEMBLEY', 72500),
 ('BRISTOL', 111250),
 ('HASSOCKS', 50000),
 ('LONDON', 78000),
 ('ROSSENDALE', 65000),
 ('NEWCASTLE UPON TYNE', 26000),
 ('USK', 91000),
 ('NORWICH', 54000),
 ('HITCHIN', 85950),
 ('CROMER', 55500),
 ('LONDON', 108000),
 ('SOLIHULL', 85000),
 ('MITCHAM', 75000),
 ('MALTON', 47500),
 ('HEREFORD', 48500),
 ('TARPORLEY', 141000),
 ('LINCOLN', 28000),
 ('HARROGATE', 116499),
 ('HEMEL HEMPSTEAD', 63000),
 ('GILLINGHAM', 53500),
 ('WEMBLEY', 83000),
 ('SPALDING', 29050),
 ('WINDSOR', 59000),
 ('CULLOMPTON', 42500),
 ('GREAT YARMOUTH', 60000),
 ('SHOREHAM-BY-SEA', 58000),
 ('KIDDERMINSTER', 52500),
 ('LONDON', 64500),
 ('CHIGWELL', 148000),
 ('WELWYN GARDEN CITY', 101950),
 ('CALDICOT', 87500),
 ('LEEDS', 55000),
 ('DEWSBURY', 52000),
 ('ROCHFORD', 89950),
 ('WESTON-SUPER-MARE', 22400),
 ('BURTON-ON-TRENT', 24200),
 ('WADHURST', 78500),
 ('BAGSHOT', 96000),
 ('BUDLEIGH SALTERTON', 69500),
 ('LINCOLN', 41000),
 ('SHEFFIELD', 20000),
 ('BARNET', 93000),
 ('BIRKENHEAD', 42000),
 ('CHEPSTOW', 82500),
 ('CLEETHORPES', 72500),
 ('ULVERSTON', 28000),
 ('NEWBURY', 54000),
 ('BURNLEY', 28000),
 ('LEICESTER', 79500),
 ('SHREWSBURY', 43000),
 ('SHEFFIELD', 27000),
 ('STEYNING', 95500),
 ('KETTERING', 22000),
 ('DURHAM', 89950),
 ('WAKEFIELD', 89000),
 ('WIMBORNE', 192000),
 ('WOLVERHAMPTON', 73950),
 ('STOKE-ON-TRENT', 14000),
 ('LONDON', 1375000),
 ('COLCHESTER', 39500),
 ('ROCHESTER', 71000),
 ('KINGSTON UPON THAMES', 83950),
 ('COLCHESTER', 42000),
 ('READING', 68000),
 ('BRIDLINGTON', 43000),
 ('BOURNEMOUTH', 49000),
 ('CARSHALTON', 59900),
 ('BILLERICAY', 138000),
 ('MIDHURST', 67000),
 ('WILMSLOW', 58750),
 ('LONDON', 900000),
 ('TIVERTON', 71000),
 ('MANCHESTER', 40000),
 ('WOKING', 178000),
 ('GRIMSBY', 46000),
 ('NEWCASTLE', 32000),
 ('SHREWSBURY', 30750),
 ('OLDHAM', 21000),
 ('NEWPORT', 20000),
 ('NORWICH', 51000),
 ('CHELMSFORD', 79500),
 ('NORTH SHIELDS', 46000),
 ('LONDON', 105000),
 ('STOCKSFIELD', 122000),
 ('NEWPORT', 27000),
 ('TIVERTON', 28190),
 ('LOUGHTON', 55000),
 ('DERBY', 32500),
 ('PETERBOROUGH', 59950),
 ('WEST MOLESEY', 158250),
 ('NEWPORT', 46950),
 ('LONDON', 68500),
 ('MANCHESTER', 65500),
 ('BOURNEMOUTH', 25500),
 ('PENZANCE', 83500),
 ('GODALMING', 365000),
 ('MAIDSTONE', 46000),
 ('EVESHAM', 52000),
 ('DOVER', 39000),
 ('WEMBLEY', 67000),
 ('SOUTH OCKENDON', 73700),
 ('TELFORD', 24600),
 ('LEAMINGTON SPA', 56000),
 ('SLOUGH', 95000),
 ('LONDON', 57000),
 ('SOUTHAMPTON', 57000),
 ('STEVENAGE', 62500),
 ('DERBY', 33000),
 ('TELFORD', 69995),
 ('DONCASTER', 82500),
 ('BOURNEMOUTH', 45000),
 ('SUTTON COLDFIELD', 60000),
 ('NORWICH', 52450),
 ('EGREMONT', 49500),
 ('DAVENTRY', 69995),
 ('BIRMINGHAM', 49950),
 ('LONDON', 110000),
 ('BRIDGEND', 75000),
 ('REDCAR', 37500),
 ('NOTTINGHAM', 36000),
 ('WORCESTER', 109000),
 ('BRISTOL', 40000),
 ('READING', 93000),
 ('DRONFIELD', 52000),
 ('BILSTON', 43000),
 ('ASHTON-UNDER-LYNE', 34950),
 ('LYDNEY', 37000),
 ('EXETER', 47000),
 ('PRENTON', 11675),
 ('SHIPLEY', 49000),
 ('FLEETWOOD', 42000),
 ('BURTON-ON-TRENT', 25000),
 ('BATH', 48000),
 ('MELTON MOWBRAY', 71000),
 ('GRAVESEND', 68000),
 ('ROCHDALE', 115000),
 ('BOURNEMOUTH', 64000),
 ('RICKMANSWORTH', 51800),
 ('SWANSEA', 37500),
 ('OSWESTRY', 156000),
 ('DERBY', 46500),
 ('LIVERPOOL', 9000),
 ('BARNSLEY', 19300),
 ('BIRMINGHAM', 49500),
 ('GLOUCESTER', 128750),
 ('BILLINGHAM', 30500),
 ('GRIMSBY', 46000),
 ('HAYWARDS HEATH', 83950),
 ('WOLVERHAMPTON', 41000),
 ('LONDON', 76000),
 ('MAIDSTONE', 36000),
 ('SHREWSBURY', 85000),
 ('WAKEFIELD', 53500),
 ('FLEET', 111000),
 ('FARINGDON', 50500),
 ('EASTBOURNE', 60000),
 ('WALSALL', 63000),
 ('GUILDFORD', 37500),
 ('WOKING', 50000),
 ('BRADFORD', 34000),
 ('CHELTENHAM', 41996),
 ('SEATON', 30000),
 ('COVENTRY', 125000),
 ('WISBECH', 132500),
 ('CHICHESTER', 57000),
 ('LICHFIELD', 56500),
 ('WOODBRIDGE', 88500),
 ('DERBY', 41000),
 ('LONDON', 98000),
 ('CAERPHILLY', 54500),
 ('TORPOINT', 22500),
 ('DORKING', 56500),
 ('LLANFYRNACH', 48000),
 ('NEWMARKET', 39000),
 ('SALFORD', 33450),
 ('ENFIELD', 108000),
 ('TIVERTON', 44250),
 ('ROWLANDS GILL', 31000),
 ('LONDON', 140000),
 ('FRESHWATER', 20000),
 ('SWANSEA', 52950),
 ('HIGH WYCOMBE', 62000),
 ('BURNLEY', 50950),
 ('BELPER', 81000),
 ('AMMANFORD', 25000),
 ('READING', 50150),
 ('LONDON', 99000),
 ('STOWMARKET', 53000),
 ('DERBY', 48950),
 ('BOGNOR REGIS', 157000),
 ('NEWTON ABBOT', 65500),
 ('EDGWARE', 194000),
 ('LONDON', 68000),
 ('BRACKLEY', 170000),
 ('HARLOW', 119950),
 ('HASTINGS', 65000),
 ('WORTHING', 78500),
 ('PETERBOROUGH', 42995),
 ('HIGH WYCOMBE', 120000),
 ('WORTHING', 48900),
 ('CANNOCK', 47300),
 ('NORWICH', 14560),
 ('LONDON', 77000),
 ('GREAT MISSENDEN', 72250),
 ('LONDON', 92000),
 ('BRACKNELL', 49500),
 ('LONDON', 121000),
 ('SHEFFIELD', 47500),
 ('SHEFFIELD', 50000),
 ('PRESTON', 17000),
 ('LEICESTER', 34000),
 ('LIVERPOOL', 33950),
 ('HOVE', 15500),
 ('WATFORD', 38495),
 ('WHITLEY BAY', 52000),
 ('MORECAMBE', 33950),
 ('ST. NEOTS', 55000),
 ('SHIFNAL', 45000),
 ('MANCHESTER', 43950),
 ('AYLESBURY', 33500),
 ('NOTTINGHAM', 38700),
 ('BEDFORD', 73500),
 ('MILTON KEYNES', 72950),
 ('STOKE-ON-TRENT', 55000),
 ('BURNHAM-ON-SEA', 41500),
 ('WREXHAM', 47000),
 ('SALISBURY', 81000),
 ('NEWBURY', 89500),
 ('WESTON-SUPER-MARE', 55500),
 ('BIRMINGHAM', 410000),
 ('SLEAFORD', 47000),
 ('BOURNEMOUTH', 100000),
 ('LONDON', 110000),
 ('SOUTH SHIELDS', 53000),
 ('MINEHEAD', 35000),
 ('WALTON-ON-THAMES', 344000),
 ('LONDON', 64000),
 ('STOCKPORT', 45500),
 ('BARRY', 28500),
 ('COTTINGHAM', 127500),
 ('LEIGHTON BUZZARD', 60000),
 ('CAMBRIDGE', 165000),
 ('DONCASTER', 23500),
 ('LONDON', 693000),
 ('CHICHESTER', 53000),
 ('DUDLEY', 42000),
 ('HYTHE', 105000),
 ('SURBITON', 92995),
 ('DONCASTER', 41500),
 ('CROYDON', 64000),
 ('SHEFFIELD', 77000),
 ('BANBURY', 33000),
 ('NORWICH', 37000),
 ('GLOUCESTER', 37000),
 ('POOLE', 70000),
 ('LONDON', 138000),
 ('LONDON', 130000),
 ('LOUGHBOROUGH', 29000),
 ('NEWCASTLE UPON TYNE', 34000),
 ('BEXLEYHEATH', 67995),
 ('LONDON', 425000),
 ('LONDON', 57786),
 ('BEXLEYHEATH', 76000),
 ('UXBRIDGE', 156250),
 ('MALVERN', 85500),
 ('PLYMOUTH', 22000),
 ('CHALFONT ST. GILES', 120500),
 ('WATFORD', 74950),
 ('HELSTON', 49000),
 ('CHESTERFIELD', 36500),
 ('STEVENAGE', 51000),
 ('HAILSHAM', 62500),
 ('ILKESTON', 80000),
 ('PRUDHOE', 51000),
 ('HARROW', 73000),
 ('ILFORD', 50500),
 ('COLCHESTER', 110000),
 ('BURY', 37000),
 ('TWICKENHAM', 88500),
 ('MAIDENHEAD', 127500),
 ('GLOUCESTER', 51000),
 ('DARLINGTON', 37750),
 ('CARSHALTON', 85000),
 ('SALTBURN-BY-THE-SEA', 55000),
 ('ROCHESTER', 39000),
 ('THATCHAM', 58700),
 ('RHYL', 29000),
 ('CHARD', 42000),
 ('BURNLEY', 73950),
 ('ASHFORD', 94500),
 ('ROMNEY MARSH', 59000),
 ('BURY', 32500),
 ('PETERSFIELD', 43000),
 ('KETTERING', 106950),
 ('BERKHAMSTED', 59950),
 ('LONDON', 63500),
 ('CLACTON-ON-SEA', 9000),
 ('LEICESTER', 35000),
 ('BIRMINGHAM', 40000),
 ('WINDLESHAM', 187000),
 ('LEICESTER', 15000),
 ('CHEADLE', 51000),
 ('WANTAGE', 58000),
 ('BIRMINGHAM', 45000),
 ('AMERSHAM', 146000),
 ('PETERLEE', 23500),
 ('SWANSEA', 47000),
 ('GLOSSOP', 60000),
 ('WIMBORNE', 71000),
 ('PENZANCE', 69000),
 ('CHESSINGTON', 69000),
 ('NUNEATON', 36000),
 ('EPSOM', 196000),
 ('KEIGHLEY', 28250),
 ('ATTLEBOROUGH', 37000),
 ('WALSALL', 32500),
 ('MANSFIELD', 28500),
 ('ROMFORD', 72000),
 ('NEWARK', 44950),
 ('YARM', 99950),
 ('ILKESTON', 39000),
 ('NOTTINGHAM', 25000),
 ('SELBY', 47500),
 ('MALMESBURY', 85000),
 ('RAYLEIGH', 99950),
 ('LONDON', 61750),
 ('BRADFORD', 21000),
 ('LONDON', 273000),
 ('EGREMONT', 25000),
 ('LEEDS', 58000),
 ('ANDOVER', 50500),
 ...]

In [ ]:
srs_prom = pd.Series(lst_prom)
srs_prom.mean(axis=0)

In [ ]:
#reducer3
dic_minimo = {}
for col,row in df_prom:
    if row['Town/City'] in dic_minimo:
        if dic_minimo[row['Town/City']] > row['Price']:
            dic_minimo[row['Town/City']] = row['Price']
    else:
        dic_minimo[row['Town/City']] = row['Price']
dic_minimo

In [ ]:
#mapper4
df_2015 = df_price[df_price['Twon/City'] == 'STAMFORD']
df_2015.drop(df_2015[df_2015['Year'] != 2015].index)
df_2015 = pd.DataFrame(df_2015['Town/City','Price'])
df_2015

In [ ]:
#reducer4
df_2015 = df_2015.sort_values('Price')

In [ ]:
#mapper